"""add language to posts

Revision ID: 755391a7cdf0
Revises: 0b088d464ef4
Create Date: 2021-07-18 19:13:19.323180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '755391a7cdf0'
down_revision = '0b088d464ef4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'language')
    # ### end Alembic commands ###
